services:
  - type: web
    name: jesko-ai-platform
    env: node
    buildCommand: npm install
    startCommand: node server-production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
