services:
  - type: web
    name: jesko-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: RUNWAY_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false